modLoader="javafml" 
loaderVersion="[39,)"
license="GNU General Public License v3.0"

[[mods]]
modId="oxidized" 
version="${file.jarVersion}"
displayName="Oxidized" 
displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
'''
[[dependencies.oxidized]]
    modId="forge" 
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
